title = "deekap.com"
base_url = "https://deekap.com"
description = "Personal website of Deepak Kapoor"

compile_sass = true
build_search_index = false
# generate_feed = true
feed_filenames =[  "atom.xml"  ]


taxonomies = [
  {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "OneHalfDark", filename = "syntax-theme-dark.css" },
  { theme = "OneHalfLight", filename = "syntax-theme-light.css" },
]

[extra]
permalinks = { blog = "/{year}/{month}/{day}/{slug}/" }
post_date_format="%d %B, %Y"
list_date_format="%d %b, %Y"
theme_toggle = true
mathjax = true
echarts = true

[[extra.main_menu]]
name = "Blog"
url = "@/blog/_index.md"

[[extra.main_menu]]
name = "About"
url = "about"

