name: Deploy to GitHub Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pelican markdown ghp-import

      - name: Build Pelican site
        run: pelican content -s publishconf.py

      - name: Copy CNAME to output
        run: |
          echo "deekap.com" > output/CNAME

      - name: Deploy to GitHub Pages
        run: |
          ghp-import -n -p -f output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
